<?php
/** @var $this \Packaged\RemarkdExample\Layout\DocPage */
?>
<div class="toc">
  <?= $this->_toc; ?>
</div>
<div class="remarkd remarkd-styled" style="padding: 20px; max-width: 900px; margin: 0 auto 0 400px;">
  <?= $this->_content; ?>
</div>
<style>
    .title {
        color: orangered;
    }

    .preamble p:first-of-type {
        font-size: 1.21875em;
        line-height: 1.6;
    }

    .listing-block, .sidebar-block, .example-block {
        margin-bottom: 1.25em;
    }

    .listing-block .content {
        white-space: pre-line;
        background: lightgray;
        padding: 10px;
    }

    .sidebar-block {
        border-style: solid;
        border-width: 1px;
        border-color: #e0e0dc;
        padding: 1.25em;
        background: #f8f8f7;
        -webkit-border-radius: 4px;
        border-radius: 4px;
    }

    .sidebar-block > .title {
        text-align: center;
        margin-top: 0;
        line-height: 1.2;
        word-spacing: -0.05em;
        font-size: 1.6875em;
        margin-bottom: 20px;
    }

    .example-block > .content {
        border-style: solid;
        border-width: 1px;
        border-color: #e6e6e6;
        padding: 1.25em;
        background: #fff;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        border-color: #e0e0dc;
        -moz-box-shadow: 0 1px 4px #e0e0dc;
        -webkit-box-shadow: 0 1px 4px #e0e0dc;
        box-shadow: 0 1px 4px #e0e0dc;
    }

    .tip-block {
        margin-left: 100px;
        background: #e1f2fa;
        border: 1px solid lightblue;
        padding: 10px;
    }

    .toc ul {
        position: fixed;
        left: 0;
        top: 0;
        padding-left: 10px;
        list-style-type: none;
    }

    .toc--1 {
        padding-left: 0;
    }

    .toc--2 {
        padding-left: 1rem;
    }

    .toc--3 {
        padding-left: 1.5rem;
    }

    .toc--4 {
        padding-left: 2rem;
    }

    .toc--5 {
        padding-left: 2.5rem;
    }

    .conum[data-value] {
        border: 1px solid;
        border-radius: 100%;
        display: inline-block;
        font-family: Roboto, sans-serif;
        font-size: .75rem;
        font-style: normal;
        line-height: 1.2;
        text-align: center;
        width: 1.25em;
        height: 1.25em;
        letter-spacing: -.25ex;
        text-indent: -.25ex;
    }

    .conum[data-value]::after {
        content: attr(data-value);
    }
</style>
