<?php

use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

$store = Dispatch::instance()->store();
/**
 * @var $this \Packaged\RemarkdExample\Layout\Wrap
 */
?>
<!doctype html>
<html lang="en">
<head>
  <title><?= $this->getContext()->meta()->get('title', 'Remarkd  Example'); ?></title>
  <meta charset="UTF-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, null, [ResourceStore::PRIORITY_LOW]) ?>
</head>
<body>
<main>
  <?= $this->getContent(); ?>
</main>
<style>
    html, body {
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        height: 100%;
        max-height: 100%;
        min-width: 720px;
    }
</style>
<?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, ResourceStore::PRIORITY_LOW) ?>
<?= $store->generateHtmlIncludes(ResourceStore::TYPE_JS); ?>
</body>
</html>
