<?php
namespace Packaged\Remarkd\Blocks;

use Packaged\Glimpse\Tags\Div;
use Packaged\Glimpse\Tags\Link;
use Packaged\Glimpse\Tags\Lists\ListItem;
use Packaged\Glimpse\Tags\Lists\UnorderedList;
use Packaged\Helpers\Arrays;
use Packaged\Helpers\Strings;
use Packaged\Ui\Html\HtmlElement;

class TabContainer extends BasicBlock
{
  protected $_contentType = Block::TYPE_COMPOUND;
  protected $_closer = '_|_';
  protected $_closeOnEmpty = false;

  public function allowLine(string $line): ?bool
  {
    return parent::allowLine($line); // TODO: Change the autogenerated stub
  }

  protected function _produceElement(): HtmlElement
  {
    $tabHeaders = UnorderedList::create()->addClass('tab-header');

    $setActive = true;
    foreach($this->children() as $child)
    {
      if($child instanceof TabBlock)
      {
        $name = Strings::titleize($child->tabID());
        if($child->_attr)
        {
          $name = $child->_attr->get('name', $name);
        }
        $link = Link::create('#', $name)->setAttribute('data-tab-focus-key', $child->tabID());
        if($setActive)
        {
          $setActive = false;
          $link->addClass('active');
        }
        $tabHeaders->appendContent(ListItem::create($link));
      }
    }

    return Div::create(
      $tabHeaders,
      Div::create(Arrays::interleave(PHP_EOL, $this->_children))->addClass('tabs')
    )->addClass('tab-group');
  }

}
